# Per-host module for sjr-fw13 — a Framework 13 AMD (Ryzen 7040).
#
# Everything machine-specific lives in this directory:
#   - hardware-configuration.nix : generated by nixos-generate-config
#                                  (root LUKS UUID, filesystems, swapDevices)
#   - this file                  : hostname, the nixos-hardware module for
#                                  this exact model, and the hibernation
#                                  swap unlock + resume target
#
# configuration.nix and home.nix are host-agnostic and shared across every
# host the flake discovers under ../. To stand up a new machine, run
# scripts/new-host.sh on it (see ../README.md) — you should not need to edit
# flake.nix at all.
{ inputs, ... }:
{
  imports = [
    ./hardware-configuration.nix

    # Maintained Framework 13 AMD Ryzen 7040 quirks (lid wake, sensors, GPU).
    # A different model picks a different module here — e.g. a Ryzen AI 300
    # would use inputs.nixos-hardware.nixosModules.framework-amd-ai-300-series.
    inputs.nixos-hardware.nixosModules.framework-13-7040-amd
  ];

  networking.hostName = "sjr-fw13";

  # Hibernation swap. This host's swap is its OWN LUKS partition (nvme0n1p3);
  # hardware-configuration.nix lists it in swapDevices, but nixos-generate-config
  # only emitted a LUKS unlock for root — so without the unlock below the swap
  # partition is never decrypted, stays at 0 B, and hibernate is impossible.
  # Unlock it and point resume at the decrypted mapper. (LUKS UUIDs are
  # identifiers, not secrets.) If swap shares root's passphrase the initrd
  # unlocks both from one prompt; otherwise expect a second prompt at boot.
  boot.initrd.luks.devices."luks-7cbba5ed-173a-4ba1-8b81-cb129f1ec8ea".device =
    "/dev/disk/by-uuid/7cbba5ed-173a-4ba1-8b81-cb129f1ec8ea";
  boot.resumeDevice = "/dev/mapper/luks-7cbba5ed-173a-4ba1-8b81-cb129f1ec8ea";
}
