# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "thunderbolt"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-184cf2ba-b284-4a04-bf75-7c4b1eb7c7d9";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-184cf2ba-b284-4a04-bf75-7c4b1eb7c7d9".device =
    "/dev/disk/by-uuid/184cf2ba-b284-4a04-bf75-7c4b1eb7c7d9";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/4E00-D664";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-7cbba5ed-173a-4ba1-8b81-cb129f1ec8ea"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
