#!/usr/bin/env bash
#
# new-host.sh — scaffold a hosts/<hostname>/ directory for a fresh machine.
#
# Run this ON the target machine, after the base NixOS install has booted and
# you've cloned this repo. It:
#   1. copies the machine's generated /etc/nixos/hardware-configuration.nix
#      into hosts/<hostname>/
#   2. writes a hosts/<hostname>/default.nix from a template (hostname filled
#      in; swap/resume UUID auto-detected from the active swap mapper when
#      possible, otherwise left as a clearly-marked TODO)
#   3. git-adds both so the flake can see them
#
# After it runs, the host is buildable as .#<hostname> — no flake.nix edit
# needed (flake.nix auto-discovers everything under hosts/). See hosts/README.md.
#
# Usage:
#   scripts/new-host.sh [hostname] [path-to-hardware-configuration.nix]
#
#   hostname  defaults to the current `hostname`
#   hw path   defaults to /etc/nixos/hardware-configuration.nix

set -euo pipefail

hostname="${1:-$(hostname)}"
hw_src="${2:-/etc/nixos/hardware-configuration.nix}"

repo_root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [ -z "$repo_root" ]; then
  echo "error: not inside a git repo. Clone this flake first, then run from inside it." >&2
  exit 1
fi

host_dir="$repo_root/hosts/$hostname"

if [ -e "$host_dir" ]; then
  echo "error: $host_dir already exists. Edit it directly, or remove it first." >&2
  exit 1
fi

if [ ! -r "$hw_src" ]; then
  echo "error: cannot read $hw_src" >&2
  echo "       Pass the path to this machine's hardware-configuration.nix as arg 2," >&2
  echo "       or run 'sudo nixos-generate-config' first." >&2
  exit 1
fi

mkdir -p "$host_dir"
cp "$hw_src" "$host_dir/hardware-configuration.nix"
chmod u+w "$host_dir/hardware-configuration.nix"

# Best-effort: derive the hibernation swap LUKS UUID. The initrd/crypttab
# mapper for an encrypted swap is conventionally named "luks-<uuid>", so if
# active swap sits on /dev/mapper/luks-<uuid> we can read the UUID straight off.
swap_block=""
swap_src="$(swapon --show=NAME --noheadings 2>/dev/null | head -n1 || true)"
swap_map="$(basename "${swap_src:-}")"
if [[ "$swap_map" == luks-* ]]; then
  swap_uuid="${swap_map#luks-}"
  swap_block=$(cat <<EOF
  # Hibernation swap, auto-detected from the active swap mapper ($swap_map).
  # nixos-generate-config lists swap in swapDevices but does not unlock it;
  # this unlock + resume target make suspend-to-disk work. Verify with
  # \`swapon --show\` and \`systemctl hibernate\`. (LUKS UUIDs aren't secrets.)
  boot.initrd.luks.devices."luks-$swap_uuid".device =
    "/dev/disk/by-uuid/$swap_uuid";
  boot.resumeDevice = "/dev/mapper/luks-$swap_uuid";
EOF
)
else
  swap_block=$(cat <<'EOF'
  # TODO(hibernation): point resume at this host's encrypted swap. Find the
  # LUKS partition UUID backing swap with:
  #     swapon --show
  #     lsblk -o NAME,TYPE,FSTYPE,UUID
  # then uncomment and fill in (drop this block entirely if you don't want
  # hibernation — suspend-to-RAM works without it):
  #
  # boot.initrd.luks.devices."luks-<swap-uuid>".device =
  #   "/dev/disk/by-uuid/<swap-uuid>";
  # boot.resumeDevice = "/dev/mapper/luks-<swap-uuid>";
EOF
)
fi

cat > "$host_dir/default.nix" <<EOF
# Per-host module for $hostname. Generated by scripts/new-host.sh.
#
# Everything machine-specific lives in this directory:
#   - hardware-configuration.nix : generated by nixos-generate-config
#   - this file                  : hostname, the nixos-hardware model module,
#                                  and the hibernation swap unlock + resume
#
# configuration.nix and home.nix are host-agnostic and shared. See
# ../README.md for the full stand-up runbook.
{ inputs, ... }:
{
  imports = [
    ./hardware-configuration.nix

    # TODO: set the nixos-hardware module for THIS machine's model. The list
    # is at https://github.com/NixOS/nixos-hardware. Default below is the
    # Framework 13 AMD Ryzen 7040 — change it if this host is different.
    inputs.nixos-hardware.nixosModules.framework-13-7040-amd
  ];

  networking.hostName = "$hostname";

$swap_block
}
EOF

git -C "$repo_root" add "hosts/$hostname/hardware-configuration.nix" "hosts/$hostname/default.nix"

echo "Scaffolded hosts/$hostname/:"
echo "  - hardware-configuration.nix (copied from $hw_src)"
echo "  - default.nix"
echo
echo "Next:"
echo "  1. Review hosts/$hostname/default.nix — set the correct nixos-hardware"
echo "     module for this model, and confirm/complete the swap block."
echo "  2. Build it:  sudo nixos-rebuild switch --flake .#$hostname"
echo "  3. Commit:    git commit -m \"hosts: add $hostname\""
